"""Added terrainType to Locations

Revision ID: 053d32637a91
Revises: d34e1049b611
Create Date: 2025-02-26 10:48:18.332298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053d32637a91'
down_revision = 'd34e1049b611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrainType', sa.Enum('Dirt', 'Rocky', 'Forest', 'Mixed', name='terrain_type_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('terrainType')

    # ### end Alembic commands ###
